# Write your MySQL query statement below
SELECT TWEET_ID #SELCT USED FOR PRIMARY KEY 
FROM TWEETS
WHERE LENGTH(CONTENT) > 15 
  AND CONTENT NOT LIKE '%[^a-zA-Z0-9]%';


#LOGIC- WE SHOULD FIND THE LENGTH OF CONTENT AND ALSO CHECK THE ALPHA NUMERICAL ARE NOT THERER IN...